### ISSUE TITLE
new collaborators

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/ledtable#7]
Hi @MasterCarl, @BlackTigers I wanted to inform you that you are both working on the project, now.
You may want to discuss what you want to do e.g. in issues so there is no conflict.

**Comment by SleepySnorlax1000** [comment]
@MasterCarl just for my own information: what is your plan at the moment? I personally work at creating more and more interesting examples. Starting with Tetris I'm thinking about making some other NES games

**Comment by MasterCarl** [comment]
@BlackTigers I'm not quite sure yet, probably some examples to display information. There shouldn't be any conflicts since I don't intend to change parts of the library itself.
